import 'package:flutter/material.dart';

Color primaryColor = const Color(0XFF274BFF);
Color primaryTextColor = const Color(0XFF284BAF);
Color blackColor = const Color(0XFF1D1D1D);
Color darkGreyColor = const Color(0XFF6D6D6D);
Color greyColor = const Color(0xff70707059);
Color lightGreyColor = const Color(0XFFE8EEF3);
Color scaffoldColor = const Color(0XFFF7F9FB);
Color tabBarColor = const Color(0XFFE1EBFF);
Color tabBarTextColor = const Color(0XFF8D98BC);
Color yellowColor = const Color(0XFFFFF940);
Color darkGreenColor = const Color(0XFF239D00);
Color darkBrown1Color = const Color(0XFF715700);
Color darkBlueColor = const Color(0XFF160056);
Color darkLightBlueColor = const Color(0XFF01299D);
Color darkBrown2Color = const Color(0XFF682A00);
Color darkPinkColor = const Color(0XFFFF2A7A);
Color orangeColor = const Color(0XFFFF4B4B);
Color cancelButtonColor = const Color(0XFF545454);
